# Generated by Django 3.2.7 on 2021-09-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amazonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amzProductName', models.CharField(blank=True, max_length=500)),
                ('amzProductPrice', models.FloatField(default=0)),
                ('amzProductRating', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='flipkartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flpProductName', models.CharField(blank=True, max_length=500)),
                ('flpProductPrice', models.FloatField(default=0)),
                ('flpProductRating', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_search', models.CharField(max_length=1000)),
            ],
        ),
    ]
