# Generated by Django 3.2.7 on 2021-09-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_amazonproduct_amzpricerange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonproduct',
            name='amzProductRating',
        ),
    ]
