# Generated by Django 3.2.7 on 2021-09-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_remove_amazonproduct_amzproductrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonproduct',
            name='amzPriceRange',
        ),
    ]
