# Generated by Django 3.2.7 on 2021-10-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_amazonproduct_amzpricerange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flipkartproduct',
            name='flpProductRating',
        ),
        migrations.AddField(
            model_name='amazonproduct',
            name='amzProductLink',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='flipkartproduct',
            name='flpProducLink',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
