# Generated by Django 3.2.7 on 2021-10-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_amazonproduct_amzimagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='flipkartproduct',
            name='flpProductImg',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
